name: CI - Python (pytest)

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - "pytest.ini"
      - "requirements*.txt"
      - ".github/workflows/python-ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "pytest.ini"
      - "requirements*.txt"

jobs:
  test:
    runs-on: ubuntu-latest

    # Evita ejecuciones solapadas en la misma rama si haces pushes seguidos
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install deps (requirements o mínimo viable)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # deps mínimas si no hay requirements.txt
            pip install pytest
          fi

      - name: Run pytest
        run: |
          pytest -q
