name: CI - Python (pytest)

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "tests/**"
      - "requirements*.txt"
      - ".github/workflows/python-ci.yml"
      - "pytest.ini"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "requirements*.txt"
      - "pytest.ini"

jobs:
  test:
    runs-on: ubuntu-latest

    # Evita colas innecesarias si haces pushes rápidos a la misma rama
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"              # Habilita caché para pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest -q

      # Opcional: sube artefactos de cobertura o logs si los generas
      # - name: Upload coverage
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: |
      #       coverage.xml
      #       .coverage
